function sunsign() {
   document.form1.date.selectedIndex;
   document.form1.month.selectedIndex;
   document.form1.sign.value;
   if (document.form1.month.selectedIndex == 1 && document.form1.date.selectedIndex <=19) {document.form1.sign.value = "Capricorn: You are conservative and afraid of taking risks. You are basically a chicken shit. There has never been a capricorn of any importance. You should just give up and end it all.";}
   if (document.form1.month.selectedIndex == 1 && document.form1.date.selectedIndex >=20) {document.form1.sign.value = "Aquarius: You have an inventive mind and are inclined to be progressive. You lie a great deal. On the other hand, you are inclined to be careless and impractical, often causing you to make the same mistake twice. People think you are a fucking jerk.";}
   if (document.form1.month.selectedIndex == 2 && document.form1.date.selectedIndex <=18) {document.form1.sign.value = "Aquarius: You have an inventive mind and are inclined to be progressive. You lie a great deal. On the other hand, you are inclined to be careless and impractical, often causing you to make the same mistake twice. People think you are a fucking jerk.";}
   if (document.form1.month.selectedIndex == 2 && document.form1.date.selectedIndex >=19) {document.form1.sign.value = "Pisces: You have a vivid imagination and you often believe that you are being followed by the F.B.I. or the C.I.A. You have little or no influence over your friends and people resent you for flaunting your power. You lack confidence and you are generally a coward. Most Pisceans are homosexual. Pisces like to screw small animals and pick their noses a lot.";}
   if (document.form1.month.selectedIndex == 3 && document.form1.date.selectedIndex <=20) {document.form1.sign.value = "Pisces: You have a vivid imagination and you often believe that you are being followed by the F.B.I. or the C.I.A. You have little or no influence over your friends and people resent you for flaunting your power. You lack confidence and you are generally a coward. Most Pisceans are homosexual. Pisces like to screw small animals and pick their noses a lot.";}
   if (document.form1.month.selectedIndex == 3 && document.form1.date.selectedIndex >=21) {document.form1.sign.value = "Aries: You are the pioneering type and hold most people in contempt. Your feelings of superiority mask your total mediocrity. You are quick tempered, impatient and scornful of advice. You are a prick.";}
   if (document.form1.month.selectedIndex == 4 && document.form1.date.selectedIndex <=20) {document.form1.sign.value = "Aries: You are the pioneering type and hold most people in contempt. Your feelings of superiority mask your total mediocrity. You are quick tempered, impatient and scornful of advice. You are a prick.";}
   if (document.form1.month.selectedIndex == 4 && document.form1.date.selectedIndex >=21) {document.form1.sign.value = "Taurus: You are practical and persistent. You possess a dogged determination and you work like hell. Most people think you are a stubborn and spoiled asshole. You are nothing but a pinko communist.";}
   if (document.form1.month.selectedIndex == 5 && document.form1.date.selectedIndex <=20) {document.form1.sign.value = "Taurus: You are practical and persistent. You possess a dogged determination and you work like hell. Most people think you are a stubborn and spoiled asshole. You are nothing but a pinko communist.";}
   if (document.form1.month.selectedIndex == 5 && document.form1.date.selectedIndex >=21) {document.form1.sign.value = "Gemini: You are a quick and intelligent thinker. People like you because you are bisexual. You are always inclined to expect too much for too little. This means you are a cheap bastard. Geminis are notorious for thriving on incest.";}
   if (document.form1.month.selectedIndex == 6 && document.form1.date.selectedIndex <=20) {document.form1.sign.value = "Gemini: You are a quick and intelligent thinker. People like you because you are bisexual. You are always inclined to expect too much for too little. This means you are a cheap bastard. Geminis are notorious for thriving on incest.";}
   if (document.form1.month.selectedIndex == 6 && document.form1.date.selectedIndex >=21) {document.form1.sign.value = "Cancer: You are both sympathetic and understanding to other people’s problems. They think you are a sucker. You always put things off ‘til later. That’s why you will always be on welfare and will never be worth a shit.";}
   if (document.form1.month.selectedIndex == 7 && document.form1.date.selectedIndex <=21) {document.form1.sign.value = "Cancer: You are both sympathetic and understanding to other people’s problems. They think you are a sucker. You always put things off ‘til later. That’s why you will always be on welfare and will never be worth a shit.";}
   if (document.form1.month.selectedIndex == 7 && document.form1.date.selectedIndex >=22) {document.form1.sign.value = "Leo: You consider yourself a born leader. Other people think you are pushy. Most Leos are bullies. You are vain and you cannot tolerate honest criticism. Your arrogance is disgusting. Leos are thieving bastards who like to kiss mirrors a lot.";}
   if (document.form1.month.selectedIndex == 8 && document.form1.date.selectedIndex <=21) {document.form1.sign.value = "Leo: You consider yourself a born leader. Other people think you are pushy. Most Leos are bullies. You are vain and you cannot tolerate honest criticism. Your arrogance is disgusting. Leos are thieving bastards who like to kiss mirrors a lot.";}
   if (document.form1.month.selectedIndex == 8 && document.form1.date.selectedIndex >=22) {document.form1.sign.value = "Virgo: You are the logical type and you hate disorder. Your constant nitpicking is sickening to your friends. You are cold, unemotional and often fall asleep while screwing. Virgos make either good bus drivers or pimps.";}
   if (document.form1.month.selectedIndex == 9 && document.form1.date.selectedIndex <=21) {document.form1.sign.value = "Virgo: You are the logical type and you hate disorder. Your constant nitpicking is sickening to your friends. You are cold, unemotional and often fall asleep while screwing. Virgos make either good bus drivers or pimps.";}
   if (document.form1.month.selectedIndex == 9 && document.form1.date.selectedIndex >=22) {document.form1.sign.value = "Libra: You are the artistic type and have a difficult time with reality. If you are a man, you are probably queer. Your chances for employment and monetary gain are excellent. Most Libra women are whores. All Libras will eventually get at least one venereal disease.";}
   if (document.form1.month.selectedIndex == 10 && document.form1.date.selectedIndex <=21) {document.form1.sign.value = "Libra: You are the artistic type and have a difficult time with reality. If you are a man, you are probably queer. Your chances for employment and monetary gain are excellent. Most Libra women are whores. All Libras will eventually get at least one venereal disease.";}
   if (document.form1.month.selectedIndex == 10 && document.form1.date.selectedIndex >=22) {document.form1.sign.value = "Scorpio: You are shrewd in business and you cannot be trusted. You shall attain the pinnacle of success, mostly because of your total lack of ethics. You are a perfect son-of-a-bitch. Most Scorpios are murdered.";}
   if (document.form1.month.selectedIndex == 11 && document.form1.date.selectedIndex <=21) {document.form1.sign.value = "Scorpio: You are shrewd in business and you cannot be trusted. You shall attain the pinnacle of success, mostly because of your total lack of ethics. You are a perfect son-of-a-bitch. Most Scorpios are murdered.";}
   if (document.form1.month.selectedIndex == 11 && document.form1.date.selectedIndex >=22) {document.form1.sign.value = "Sagittarius: You are optimistic and enthusiastic. You exhibit a reckless tendency to rely on your looks, mostly because you have no talent. The majority of Sagittarians are either drunks or pot heads. People often laugh at you because you are constantly getting fucked over.";}
   if (document.form1.month.selectedIndex == 12 && document.form1.date.selectedIndex <=20) {document.form1.sign.value = "Sagittarius: You are optimistic and enthusiastic. You exhibit a reckless tendency to rely on your looks, mostly because you have no talent. The majority of Sagittarians are either drunks or pot heads. People often laugh at you because you are constantly getting fucked over.";}
   if (document.form1.month.selectedIndex == 12 && document.form1.date.selectedIndex >=21) {document.form1.sign.value = "Capricorn: You are conservative and afraid of taking risks. You are basically a chicken shit. There has never been a capricorn of any importance. You should just give up and end it all.";}

   if (document.form1.month.selectedIndex == "x" || document.form1.date.selectedIndex == "y") return;
 }

function validate() {
   if (document.form1.month.selectedIndex == 2 && document.form1.date.selectedIndex > 29) {alert("There are only a maximum of 29 days in February."); return false;}
   if (document.form1.month.selectedIndex == 4 && document.form1.date.selectedIndex == 31) {alert("There are only 30 days in April."); return false;}
   if (document.form1.month.selectedIndex == 6 && document.form1.date.selectedIndex == 31) {alert("There are only 30 days in June."); return false;}
   if (document.form1.month.selectedIndex == 9 && document.form1.date.selectedIndex == 31) {alert("There are only 30 days in September."); return false;}
   if (document.form1.month.selectedIndex == 11 && document.form1.date.selectedIndex == 31) {alert("There are only 30 days in November."); return false;}
else{
return true;
}
 }



